### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by realth000** [realth000/tsdm_client#3]
# 1.0版本目标

## Feature

* [x] BBCode编辑器
  * [x] 基本功能
  * [x] 帖子页中限制功能
  * [x] 私信页中限制功能
  * ~~服务器字体（只设置代码，不改变外观）~~ 不再支持字体
  * [x] Image provider *override* f34e618
  * [x] Color picker *override* af2ad5c
  * [x] Url picker *override* fdab6d5
  * [x] Image按照设置的~~大小尺寸~~比例显示 8a56011
  * [x] Image设置额外的边界尺寸，防止过大/过小 8a56011
  * [x] Image上显示尺寸标识 8a56011
  * [x] Image自动检查并填充图片大小 1cda787
  * [x] 限制表情的大小尺寸 e15e953
  * [x] 编辑器焦点
  * [x] 复制/导入/导出为BBCode/Quill Delta e938faa
  * ~~BBCode解析为delta并显示为解析后的样式~~ *遗留到后续版本*
  * ~~纯文本编辑模式~~ *遗留到后续版本*
  * [x] 帖子中带所有功能的编辑 *工具栏会很长，看是单独用一个全屏的页面还是当前页面直接占全屏*
  * ~~帖子页中的工具栏可自定义要显示的样式功能~~ *遗留到后续版本*
  * [x] 提醒用户（@）的文本作为一个整体 d36fd13
  * [x] 提醒用户（@）时搜索用户名和好友，保持和服务器行为一致
  * ~~插入表情后编辑器没有恢复焦点~~
  * [x] 字号菜单向下展开会被键盘挡住 484517a
  * [x] 提醒页面回复消息时，收起编辑器会导致回复目标楼层被清除，变成回复帖子
  * ~~快速回复~~ 鸽了
  * [x] 折叠区域 559a004
  * [x] 隐藏区域 3acea63
  * ~~音乐（网易云）~~ *遗留到后续版本*
  * ~~视频（bilibili）~~ *遗留到后续版本*
* [x] 发帖
  * [x] 基本功能 cd7b015
  * [x] 发帖前强制提示：所在分区、当前账户 cd7b015
  * ~~本地自动保存~~ *遗留到后续版本*
  * [x] 保存为草稿 cd7b015
  * [x] 编辑草稿 b0ffe62
  * [x] 服务器草稿同步 cd7b015
* [x] 登录
  * [x] 邮箱或UID登录
  * [x] 登录失败时自动刷新验证码 618b55a
  * ~~自动拉取登录验证问题~~ 写死
  * [x] api登录
  * [x] 数据库不再保存email，并且在切换账户登录时，不检查相同账户是否用不同的login field登录的情况
    * 如果拿到凭据后，确实已登录过，是否要将先前的凭据通知服务器失效掉
    * 可以有效加快登录和打开app后页面加载速度
* [x] html解析
  * [x] 解析文字背景色
  * ~~解析上标~~ *遗留到后续版本*
* [x] 首页
  * [x] 迁移至[官方实现的轮播图](https://main-api.flutter.dev/flutter/material/CarouselView-class.html) 317b7b6
* [x] 帖子
  * ~~用户简要信息中显示勋章和签名档~~
  * [x] 重构页面，修复白屏滚动问题 be42e89
  * [x] 深色模式将帖子中的浅色转换为深色 9c254a9
  * ~~顶部下拉加载更多，代替刷新~~ *遗留到后续版本*
  * [x] 从消息页跳转而来时滚动到相应消息楼层。 d4763c0
  * [x] 从解析网址跳转到对应某一楼层时滚动到相应消息楼层 5e98d0a
  * [x] 自动滚动到相应楼层 d4763c0
  * [x] 未登录或帖子已关闭时回复栏无提醒。 099dbea
* [x] 显式地使用和处理异常 24687e5
* [x] 添加logger代替`debug` 5310069
* [x] 迁移到drift 5310069
* [x] 针对旧版本升级场景，清除弃用的isar数据库并给出提示。 0fafa26
* [x] 收起回复框时清理回复目标的逻辑需要调整，并且在回复提醒的页面内不清楚相关参数
* ~~支持Web平台~~ *遗留到后续版本*
  * ~~Wasm~~
  * ~~Javascript~~
* ~~单独保存和加载用户头像，以在无头像的位置显示缓存的头像~~ *遗留到后续版本*
* ~~ImageProvider加载失败时支持重新加载~~ *遗留到后续版本*
* ~~头像，ImageProvider支持那些可在Image上进行的操作~~ *遗留到后续版本*
* [x] 缓存通知，包括提醒/私人消息/公共消息
* ~~数据导入/导出~~ *遗留到后续版本*
* ~~图片缓存进一步分类，不同分类持有不同的有效时间~~ *遗留到后续版本*
  * 缓存移动到数据目录
  * 定时清理
* [x] 缓存所有用户头像，使得在没有用户头像的地方也可以用上 f96cc7b
  * ~~要先实现图片分类~~
  * 可能要先把image缓存刷新的功能在image provider上实现一遍，先不实现也行
* [x] 多用户及切换 1d17448
* [x] 自动签到 fe8e045
* ~~显示帖子是否（在本机）回复过~~ 鸽了

## Bugfix

* [x] 全局Dio Exception异常处理 24687e5
* ~~跳转到帖子链接后页面内无标题~~
* [x] 跳转到帖子链接后无法切换楼层排序 e1e58dc
* [x] 跳转到帖子链接后加载一下的页数不正确 b77dcfe
* [x] 加载帖子新页数后，右上角变成最新加载的页数，无论当前屏幕位置在哪。 9ae20b5
* [x] 图片缓存失效后自动重新下载 8baa166
* [x] 评分区域中头像无法加载时无限加载 8d53245
* [x] 图片加载失败时依然显示加载中 ce1a903
* [x] 减少图片加载时的闪烁 5bd3d93
* [x] ImageProvider加载失败时显示默认图片 70179b6
* [x] html解析
  * [x] 折叠区域内，文本中文字样式丢失
  * [x] 折叠区域尾部多余换行 8a5fc75
  * [x] 更新解析为带按钮的样式的外观 a5ae204
  * [x] 表格样式 240ec48
  * [x] 解析音乐（网易云）247cdf3b
  * [x] 新人报道表格 77a5257
* [x] 帖子
  * [x] 筛选后不显示置顶帖 0dff03f
  * [x] 用户信息dialog中腹黑的值写成天然 b18e75e

**Comment by Qing-Novel** [comment]
佬，想问下帖子内用户简要信息中显示勋章和签名档是放弃制作了吗？我看到1.0目标里划掉了，且没标注遗留到后续版本字样

**Comment by realth000** [comment]
> 佬，想问下帖子内用户简要信息中显示勋章和签名档是放弃制作了吗？我看到1.0目标里划掉了，且没标注遗留到后续版本字样

现在的网页很难处理楼层用户资料里的勋章，API没有提供，后续看看怎么办吧。1.0之后很快要把拉取帖子的方式切到API，这样会快很多，也稳定。

**Comment by Qing-Novel** [comment]
> > 佬，想问下帖子内用户简要信息中显示勋章和签名档是放弃制作了吗？我看到1.0目标里划掉了，且没标注遗留到后续版本字样
> 
> 现在的网页很难处理楼层用户资料里的勋章，API没有提供，后续看看怎么办吧。1.0之后很快要把拉取帖子的方式切到API，这样会快很多，也稳定。
> 
> 所以这俩功能暂时不加了

明白了

**Comment by Qing-Novel** [comment]
1.0快做完了，感觉可以出2.0的目标了😋

**Comment by realth000** [comment]
> 1.0快做完了，感觉可以出2.0的目标了😋

理想状态下不会有2.0，除非又要引入破坏性变更。
这次1.0是迫于无奈（

**Comment by Qing-Novel** [comment]
> > 1.0快做完了，感觉可以出2.0的目标了😋
> 
> 理想状态下不会有2.0，除非又要引入破坏性变更。 这次1.0是迫于无奈（

那时候就还是1.0然后慢慢加功能了？
话说这次的破坏性变更是什么内容？

**Comment by Qing-Novel** [comment]
> 能一点一点往后慢慢迭代就行，事实证明这个roadmap一直在改，很随意，实际效果只有告诉别人这个项目还在更新（

2333也就是所谓的我还在是吧

**Comment by realth000** [comment]
丢数据，底层用的数据库换掉了，之前的数据保留不了。

要说的话还有很多功能可以加，不过着急的或者说基础功能都有了。

其实从习惯上来说1.0版本还是要有的，证明已经有足够的基础功能和稳定性了，2.0除非有很大的变动，不然一直保持1.x也一样，咱这个没有kpi要求，不需要刷版本号骗用户更新。

**Comment by Qing-Novel** [comment]
> 丢数据，底层用的数据库换掉了，之前的数据保留不了。
> 
> 要说的话还有很多功能可以加，不过着急的或者说基础功能都有了。
> 
> 其实从习惯上来说1.0版本还是要有的，证明已经有足够的基础功能和稳定性了，2.0除非有很大的变动，不然一直保持1.x也一样，咱这个没有kpi要求，不需要刷版本号骗用户更新。

原来如此，那改动确实挺大
确实基础功能有了，后面慢慢来就是了
那确实，国外的app版本那叫一个多，几天就来一个

**Comment by Qing-Novel** [comment]
好家伙，没想到今天就完结了1.0的目标
